# yaml-language-server: $schema=https://render.com/schema/render.yaml.json
services:
  - type: web
    name: orisync-dev
    runtime: docker
    plan: free
    branch: dev
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Staging
