// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OriSync.Api.Data;

#nullable disable

namespace OriSync.Api.Data.Migrations
{
    [DbContext(typeof(OriSyncDbContext))]
    [Migration("20261008200649_AddPasswordResetEmailOutbox")]
    partial class AddPasswordResetEmailOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("OriSync.Api.Domain.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("CurrentGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_group_id");

                    b.Property<DateTimeOffset?>("DeletionEligibleAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_eligible_at");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<string>("RecoveryCodeHash")
                        .HasColumnType("text")
                        .HasColumnName("recovery_code_hash");

                    b.Property<DateTimeOffset?>("RecoveryCodeIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recovery_code_issued_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("CurrentGroupId")
                        .HasDatabaseName("ix_accounts_current_group_id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_person_id");

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_role")
                        .HasFilter("role = 'Admin'");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounts_admin_group", "role <> 'Admin' OR current_group_id IS NULL");

                            t.HasCheckConstraint("ck_accounts_password_hash", "btrim(password_hash) <> ''");

                            t.HasCheckConstraint("ck_accounts_role", "role IN ('Admin', 'Mentor')");
                        });
                });

            modelBuilder.Entity("OriSync.Api.Domain.AccountSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("text")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("AbsoluteExpiresAt")
                        .HasDatabaseName("ix_sessions_absolute_expires_at")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_one_active_per_account")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_token_hash");

                    b.ToTable("sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_sessions_times", "last_seen_at >= created_at AND absolute_expires_at > created_at");

                            t.HasCheckConstraint("ck_sessions_token_hash", "btrim(token_hash) <> ''");
                        });
                });

            modelBuilder.Entity("OriSync.Api.Domain.AttendanceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<string>("CaptureMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Automatic")
                        .HasColumnName("capture_method");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<long?>("MarkedByAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("marked_by_account_id");

                    b.Property<long>("OrientationId")
                        .HasColumnType("bigint")
                        .HasColumnName("orientation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Absent")
                        .HasColumnName("status");

                    b.Property<long>("StudentEnrollmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_enrollment_id");

                    b.HasKey("Id")
                        .HasName("pk_attendance_records");

                    b.HasIndex("MarkedByAccountId")
                        .HasDatabaseName("ix_attendance_records_marked_by_account_id");

                    b.HasIndex("GroupId", "OrientationId")
                        .HasDatabaseName("ix_attendance_records_group_id_orientation_id");

                    b.HasIndex("StudentEnrollmentId", "AttendanceDate")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_records_student_enrollment_id_attendance_date");

                    b.HasIndex("StudentEnrollmentId", "OrientationId")
                        .HasDatabaseName("ix_attendance_records_student_enrollment_id_orientation_id");

                    b.HasIndex("GroupId", "AttendanceDate", "Status")
                        .HasDatabaseName("ix_attendance_records_group_id_attendance_date_status");

                    b.HasIndex("OrientationId", "AttendanceDate", "Status")
                        .HasDatabaseName("ix_attendance_records_orientation_id_attendance_date_status");

                    b.ToTable("attendance_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_attendance_records_capture_method", "capture_method IN ('Automatic', 'Qr', 'Manual', 'Registration')");

                            t.HasCheckConstraint("ck_attendance_records_status", "status IN ('Absent', 'Present')");
                        });
                });

            modelBuilder.Entity("OriSync.Api.Domain.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_audit_events_account_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_audit_events_expires_at");

                    b.ToTable("audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_events_entity_type", "btrim(entity_type) <> ''");

                            t.HasCheckConstraint("ck_audit_events_event_type", "btrim(event_type) <> ''");

                            t.HasCheckConstraint("ck_audit_events_expiry", "expires_at > occurred_at");
                        });
                });

            modelBuilder.Entity("OriSync.Api.Domain.Orientation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<TimeOnly>("AttendanceClosesAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("attendance_closes_at");

                    b.Property<TimeOnly>("AttendanceOpensAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("attendance_opens_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PurgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purged_at");

                    b.Property<DateTimeOffset>("RetentionDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_due_at");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Africa/Johannesburg")
                        .HasColumnName("time_zone_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_orientations");

                    b.HasIndex("RetentionDueAt")
                        .HasDatabaseName("ix_orientations_retention_due_at")
                        .HasFilter("purged_at IS NULL");

                    b.HasIndex("Year")
                        .IsUnique()
                        .HasDatabaseName("ix_orientations_year");

                    b.ToTable("orientations", null, t =>
                        {
                            t.HasCheckConstraint("ck_orientations_dates", "start_date <= end_date");

                            t.HasCheckConstraint("ck_orientations_hours", "attendance_opens_at < attendance_closes_at");

                            t.HasCheckConstraint("ck_orientations_name", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_orientations_retention", "retention_due_at > created_at");

                            t.HasCheckConstraint("ck_orientations_timezone", "btrim(time_zone_id) <> ''");

                            t.HasCheckConstraint("ck_orientations_year", "year BETWEEN 2020 AND 2200");
                        });
                });

            modelBuilder.Entity("OriSync.Api.Domain.OrientationGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.Property<long>("OrientationId")
                        .HasColumnType("bigint")
                        .HasColumnName("orientation_id");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasAlternateKey("Id", "OrientationId")
                        .HasName("ak_groups_id_orientation_id");

                    b.HasIndex("OrientationId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_groups_orientation_id_normalized_name");

                    b.ToTable("groups", null, t =>
                        {
                            t.HasCheckConstraint("ck_groups_name", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_groups_normalized_name", "normalized_name = lower(btrim(name))");
                        });
                });

            modelBuilder.Entity("OriSync.Api.Domain.PasswordResetEmailOutbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DiscardAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discard_after");

                    b.Property<DateTimeOffset?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discarded_at");

                    b.Property<long>("PasswordResetOtpId")
                        .HasColumnType("bigint")
                        .HasColumnName("password_reset_otp_id");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_email");

                    b.Property<string>("RecipientFirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_first_name");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_email_outbox");

                    b.HasIndex("DiscardAfter")
                        .HasDatabaseName("ix_password_reset_email_outbox_discard_after")
                        .HasFilter("sent_at IS NULL AND discarded_at IS NULL");

                    b.HasIndex("PasswordResetOtpId")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_email_outbox_password_reset_otp_id");

                    b.HasIndex("AvailableAt", "Id")
                        .HasDatabaseName("ix_password_reset_email_outbox_available_at_id")
                        .HasFilter("sent_at IS NULL AND discarded_at IS NULL");

                    b.ToTable("password_reset_email_outbox", null, t =>
                        {
                            t.HasCheckConstraint("ck_password_reset_email_outbox_attempts", "attempt_count BETWEEN 0 AND 20");

                            t.HasCheckConstraint("ck_password_reset_email_outbox_name", "btrim(recipient_first_name) <> ''");

                            t.HasCheckConstraint("ck_password_reset_email_outbox_recipient", "position('@' in recipient_email) > 1");

                            t.HasCheckConstraint("ck_password_reset_email_outbox_terminal_state", "sent_at IS NULL OR discarded_at IS NULL");

                            t.HasCheckConstraint("ck_password_reset_email_outbox_times", "available_at >= created_at AND discard_after > created_at AND (sent_at IS NULL OR sent_at >= created_at) AND (discarded_at IS NULL OR discarded_at >= created_at)");
                        });
                });

            modelBuilder.Entity("OriSync.Api.Domain.PasswordResetOtp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<string>("CodeNonce")
                        .HasColumnType("text")
                        .HasColumnName("code_nonce");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_otps");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_password_reset_otps_expires_at");

                    b.HasIndex("AccountId", "RequestedAt")
                        .HasDatabaseName("ix_password_reset_otps_account_id_requested_at");

                    b.ToTable("password_reset_otps", null, t =>
                        {
                            t.HasCheckConstraint("ck_password_reset_otps_code_hash", "btrim(code_hash) <> ''");

                            t.HasCheckConstraint("ck_password_reset_otps_failed_attempts", "failed_attempts BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_password_reset_otps_times", "((sent_at IS NULL AND expires_at IS NULL) OR (sent_at IS NOT NULL AND expires_at > sent_at)) AND (consumed_at IS NULL OR consumed_at >= requested_at)");
                        });
                });

            modelBuilder.Entity("OriSync.Api.Domain.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgeGroup")
                        .HasColumnType("text")
                        .HasColumnName("age_group");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("text")
                        .HasColumnName("ethnicity");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("Initials")
                        .HasColumnType("text")
                        .HasColumnName("initials");

                    b.Property<string>("InstitutionNumber")
                        .HasColumnType("text")
                        .HasColumnName("institution_number");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("person_type");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("InstitutionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_people_institution_number");

                    b.HasIndex("Surname", "FirstName")
                        .HasDatabaseName("ix_people_surname_first_name");

                    b.ToTable("people", null, t =>
                        {
                            t.HasCheckConstraint("ck_people_age_group", "age_group IS NULL OR age_group IN ('C1', 'C2', 'C3', 'C4', 'C5')");

                            t.HasCheckConstraint("ck_people_ethnicity", "ethnicity IS NULL OR ethnicity IN ('White', 'African', 'Coloured', 'Indian', 'Other')");

                            t.HasCheckConstraint("ck_people_first_name", "btrim(first_name) <> ''");

                            t.HasCheckConstraint("ck_people_gender", "gender IS NULL OR gender IN ('Male', 'Female', 'Other')");

                            t.HasCheckConstraint("ck_people_institution_number", "institution_number IS NULL OR institution_number ~ '^2[0-9]{8}$'");

                            t.HasCheckConstraint("ck_people_number_required", "person_type = 'Admin' OR institution_number IS NOT NULL");

                            t.HasCheckConstraint("ck_people_student_fields", "person_type <> 'Student' OR (initials IS NOT NULL AND btrim(initials) <> '' AND age_group IS NOT NULL AND gender IS NOT NULL AND ethnicity IS NOT NULL)");

                            t.HasCheckConstraint("ck_people_surname", "btrim(surname) <> ''");

                            t.HasCheckConstraint("ck_people_type", "person_type IN ('Admin', 'Mentor', 'Student')");
                        });
                });

            modelBuilder.Entity("OriSync.Api.Domain.PersonEmail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_type");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("pk_person_emails");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_person_emails_normalized_email");

                    b.HasIndex("PersonId", "EmailType")
                        .IsUnique()
                        .HasDatabaseName("ix_person_emails_person_id_email_type");

                    b.ToTable("person_emails", null, t =>
                        {
                            t.HasCheckConstraint("ck_person_emails_format", "position('@' in email) > 1");

                            t.HasCheckConstraint("ck_person_emails_normalized", "normalized_email = lower(btrim(email))");

                            t.HasCheckConstraint("ck_person_emails_type", "email_type IN ('Student', 'Personal', 'Login')");
                        });
                });

            modelBuilder.Entity("OriSync.Api.Domain.StudentEnrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CurrentGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_group_id");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("OrientationId")
                        .HasColumnType("bigint")
                        .HasColumnName("orientation_id");

                    b.Property<DateOnly?>("PendingGroupEffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("pending_group_effective_date");

                    b.Property<long?>("PendingGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("pending_group_id");

                    b.Property<int>("QrVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("qr_version");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_student_enrollments");

                    b.HasAlternateKey("Id", "OrientationId")
                        .HasName("ak_student_enrollments_id_orientation_id");

                    b.HasIndex("CurrentGroupId")
                        .HasDatabaseName("ix_student_enrollments_current_group_id");

                    b.HasIndex("PendingGroupId")
                        .HasDatabaseName("ix_student_enrollments_pending_group_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_student_enrollments_student_id");

                    b.HasIndex("CurrentGroupId", "OrientationId")
                        .HasDatabaseName("ix_student_enrollments_current_group_id_orientation_id");

                    b.HasIndex("OrientationId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_enrollments_unassigned")
                        .HasFilter("current_group_id IS NULL AND removed_at IS NULL");

                    b.HasIndex("PendingGroupId", "OrientationId")
                        .HasDatabaseName("ix_student_enrollments_pending_group_id_orientation_id");

                    b.ToTable("student_enrollments", null, t =>
                        {
                            t.HasCheckConstraint("ck_student_enrollments_pending_group", "(pending_group_id IS NULL) = (pending_group_effective_date IS NULL)");

                            t.HasCheckConstraint("ck_student_enrollments_qr_version", "qr_version > 0");
                        });
                });

            modelBuilder.Entity("OriSync.Api.Domain.Account", b =>
                {
                    b.HasOne("OriSync.Api.Domain.OrientationGroup", "CurrentGroup")
                        .WithMany()
                        .HasForeignKey("CurrentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_accounts_groups_current_group_id");

                    b.HasOne("OriSync.Api.Domain.Person", "Person")
                        .WithOne()
                        .HasForeignKey("OriSync.Api.Domain.Account", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_people_person_id");

                    b.Navigation("CurrentGroup");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("OriSync.Api.Domain.AccountSession", b =>
                {
                    b.HasOne("OriSync.Api.Domain.Account", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OriSync.Api.Domain.AttendanceRecord", b =>
                {
                    b.HasOne("OriSync.Api.Domain.Account", "MarkedByAccount")
                        .WithMany()
                        .HasForeignKey("MarkedByAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_attendance_records_accounts_marked_by_account_id");

                    b.HasOne("OriSync.Api.Domain.OrientationGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId", "OrientationId")
                        .HasPrincipalKey("Id", "OrientationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_records_groups_group_id_orientation_id");

                    b.HasOne("OriSync.Api.Domain.StudentEnrollment", "StudentEnrollment")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentEnrollmentId", "OrientationId")
                        .HasPrincipalKey("Id", "OrientationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_records_student_enrollments_student_enrollment_i");

                    b.Navigation("Group");

                    b.Navigation("MarkedByAccount");

                    b.Navigation("StudentEnrollment");
                });

            modelBuilder.Entity("OriSync.Api.Domain.AuditEvent", b =>
                {
                    b.HasOne("OriSync.Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_events_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OriSync.Api.Domain.OrientationGroup", b =>
                {
                    b.HasOne("OriSync.Api.Domain.Orientation", "Orientation")
                        .WithMany("Groups")
                        .HasForeignKey("OrientationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_groups_orientations_orientation_id");

                    b.Navigation("Orientation");
                });

            modelBuilder.Entity("OriSync.Api.Domain.PasswordResetEmailOutbox", b =>
                {
                    b.HasOne("OriSync.Api.Domain.PasswordResetOtp", "PasswordResetOtp")
                        .WithOne("EmailOutbox")
                        .HasForeignKey("OriSync.Api.Domain.PasswordResetEmailOutbox", "PasswordResetOtpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_email_outbox_password_reset_otps_password_re");

                    b.Navigation("PasswordResetOtp");
                });

            modelBuilder.Entity("OriSync.Api.Domain.PasswordResetOtp", b =>
                {
                    b.HasOne("OriSync.Api.Domain.Account", "Account")
                        .WithMany("PasswordResetOtps")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_otps_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OriSync.Api.Domain.PersonEmail", b =>
                {
                    b.HasOne("OriSync.Api.Domain.Person", "Person")
                        .WithMany("Emails")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_emails_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("OriSync.Api.Domain.StudentEnrollment", b =>
                {
                    b.HasOne("OriSync.Api.Domain.Orientation", "Orientation")
                        .WithMany("StudentEnrollments")
                        .HasForeignKey("OrientationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_enrollments_orientations_orientation_id");

                    b.HasOne("OriSync.Api.Domain.Person", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_enrollments_people_student_id");

                    b.HasOne("OriSync.Api.Domain.OrientationGroup", "CurrentGroup")
                        .WithMany()
                        .HasForeignKey("CurrentGroupId", "OrientationId")
                        .HasPrincipalKey("Id", "OrientationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_student_enrollments_groups_current_group_id_orientation_id");

                    b.HasOne("OriSync.Api.Domain.OrientationGroup", "PendingGroup")
                        .WithMany()
                        .HasForeignKey("PendingGroupId", "OrientationId")
                        .HasPrincipalKey("Id", "OrientationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_student_enrollments_groups_pending_group_id_orientation_id");

                    b.Navigation("CurrentGroup");

                    b.Navigation("Orientation");

                    b.Navigation("PendingGroup");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OriSync.Api.Domain.Account", b =>
                {
                    b.Navigation("PasswordResetOtps");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("OriSync.Api.Domain.Orientation", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("StudentEnrollments");
                });

            modelBuilder.Entity("OriSync.Api.Domain.PasswordResetOtp", b =>
                {
                    b.Navigation("EmailOutbox");
                });

            modelBuilder.Entity("OriSync.Api.Domain.Person", b =>
                {
                    b.Navigation("Emails");
                });

            modelBuilder.Entity("OriSync.Api.Domain.StudentEnrollment", b =>
                {
                    b.Navigation("AttendanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
